language: cpp
addons:
  apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - g++
    - clang
    - libgl1-mesa-dev
compiler:
  - clang
dist: bionic
os:
  - linux
before_install:
  - sudo apt install cmake=3.16.3-1ubuntu1
  - sudo apt-get install pkg-config
  - sudo apt-get install libx11-dev
  - sudo apt-get install libxcb1-dev
  - sudo apt-get install libxkbfile-dev
  - sudo apt-get install libxkbcommon-dev
  - sudo apt-get install libxkbcommon-x11-dev
  - sudo apt-get install libx11-xcb1
  - sudo apt-get install libxkbfile1
  - sudo apt-get install libxss1
  - sudo apt-get install libxtst-dev

script:


  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .
