language: cpp
addons:
  apt_packages:
    - libxrandr-dev
    - libudev-dev
    - g++-8
    - libgl1-mesa-dev
    - libxcursor-dev
compiler:
  - gcc
dist: bionic
services:
  - xvfb
os:
  - linux
before_install:
  - version=3.17
  - build=3-Linux-x86_64
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - sudo apt-get install libxkbfile-dev
  - sudo apt-get install libxkbcommon-dev
  - sudo apt-get install libxkbcommon-x11-dev
  - sudo apt-get install libxtst-dev
  - sudo apt-get install libxinerama-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
  - version=3.17
  - build=3-Linux-x86_64
  - cd /home/travis/build/asakhar/multi-clipboard
  - mkdir -p build
  - cd build
  - ~/temp/cmake-$version.$build/bin/cmake ..
  - ~/temp/cmake-$version.$build/bin/cmake --build .
  - ctest
