language: cpp
addons:
  apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - g++
    - clang
    - libgl1-mesa-dev
compiler:
  - clang
dist: bionic
os:
  - linux
before_install:
  - version=3.17
  - build=3-Linux-x86_64
  - pwd
  

script:
  - version=3.17
  - build=3-Linux-x86_64
  - mkdir -p build
  - cd build
  - ~/temp/cmake-$version.$build/bin/cmake ..
  - ~/temp/cmake-$version.$build/bin/cmake --build .
