language: cpp
addons:
  apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - g++
    - libgl1-mesa-dev
compiler:
  - clang-10
dist: bionic
os:
  - linux
before_install:
  - sudo add-apt-repository main
  - sudo add-apt-repository universe
  - sudo add-apt-repository restricted
  - sudo add-apt-repository multiverse
  - version=3.17
  - build=3-Linux-x86_64
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - sudo apt-get install pkg-config
  - sudo apt-get install libx11-dev
  - sudo apt-get install libxcb1-dev
  - sudo apt-get install libxkbfile-dev
  - sudo apt-get install libxkbcommon-dev
  - sudo apt-get install libxkbcommon-x11-dev
  - sudo apt-get install libx11-xcb1
  - sudo apt-get install libxkbfile1
  - sudo apt-get install libxss1
  - sudo apt-get install libxtst-dev
  - sudo apt-get install libxinerama-dev

script:
  - version=3.17
  - build=3-Linux-x86_64
  - cd /home/travis/build/asakhar/multi-clipboard
  - mkdir -p build
  - cd build
  - ~/temp/cmake-$version.$build/bin/cmake ..
  - ~/temp/cmake-$version.$build/bin/cmake --build .
