language: cpp
compiler:
  - clang
dist: bionic
os:
  - linux
before_install:
  - sudo apt-get -y install libx11-dev
  - sudo apt-get -y install libxkbfile-dev
  - sudo apt-get -y install libxkbcommon-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .