language: cpp
compiler:
  - clang
dist: bionic
os:
  - linux
script:
  - sudo apt-get -y install libx11-dev
  - sudo apt-get -y install libxcb1-dev
  - sudo apt-get -y install libxkbfile-dev
  - sudo apt-get -y install libxkbcommon-dev
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .